### ISSUE TITLE
支持wav格式的吗

### ISSUE THREAD

**Issue by mkxj** [w3c/media-source#244] opened 2019-10-21 06:40 UTC
支持wav格式的吗，如果支持，mime咋写，是audio/wav吗

**Comment by guest271314** [comment] 2020-01-29 22:37
Not currently `MediaSource.isTypeSupported("audio/wav")` returns `false` at Firefox and Chromium. 

If the WAV file is formatted as `Float32Array`s it is possible to stream the audio using Web Audio API `AudioWorkletProcessor`.

**Comment by wolenetz** [comment] 2020-01-29 22:45
This is a duplicate of #55 
Thank you for the report. We are considering feature requests like this for possible inclusion in the next version of MSE.

**Closed by wolenetz** 2020-01-29 22:45 UTC
