### ISSUE TITLE
Ambiguous behaviour when running the range removal algorithm

### ISSUE THREAD

**Issue by wolenetz** [w3c/media-source#29] opened 2015-10-13 23:17 UTC
Migrated from w3c bugzilla tracker. For history prior to migration, please see:
https://www.w3.org/Bugs/Public/show_bug.cgi?id=28877

**Comment by jdsmith3000** [comment] 2015-10-19 23:45
We might want to consider marking this "needs implementation", since we've agreed to clarify these steps:

 1. Unset the last decode timestamp on all track buffers.
 2. Unset the last frame duration on all track buffers.
 3. Unset the highest end timestamp on all track buffers.
 4. Set the need random access point flag on all track buffers to true.

**Comment by jdsmith3000** [comment] 2015-10-28 05:42
Here's the context of the steps we've agreed (from Matt's proposal):

I suggest amending the coded frame removal, following step 4, and prior to step 5 (which would become step 6) with something like:

If the last decode timestamp for track buffer is set and if any of the coded frames removed in the previous step have a decode timestamp that equals to the last decode timestamp:
 1. Unset the last decode timestamp on all track buffers.
 2. Unset the last frame duration on all track buffers.
 3. Unset the highest end timestamp on all track buffers.
 4. Set the need random access point flag on all track buffers to true.

These steps require resuming with a random access point, which should address the concern in the bug about resuming at unplayable positions in the range.

**Comment by wolenetz** [comment] 2015-10-28 20:32
That sounds good to me (akin to my proposal in https://www.w3.org/Bugs/Public/show_bug.cgi?id=28557#c1). To clarify, these steps would be added to the frame removal algorithm when [the frame being removed has] decode timestamp == the last decode timestamp [for that frame's track].

**Comment by jdsmith3000** [comment] 2016-02-05 00:11
I believe this issue is a duplicate of issue #23 Coded frame removal algorithm may introduce discontinuity at end of current coded frame group and has the same intended fix.  That fix is currently being reviewed in PR #47.  

I am resolving this issue as a duplicate.  If additional work is needed, please re-open and clarify.

**Closed by jdsmith3000** 2016-02-05 00:11 UTC
Labels: needs follow-up, needs implementation
