### ISSUE TITLE
Can we expose MediaSource in DedicatedWorkerGlobalScope and SharedWorkerGlobalScope?

### ISSUE THREAD

**Issue by guest271314** [w3c/media-source#192] opened 2017-08-30 00:46 UTC
Can we expose MediaSource in DedicatedWorkerGlobalScope and SharedWorkerGlobalScope? 

Use cases include requesting, processing and editing media in a different context which could be posted to a separate context or server.

**Comment by wolenetz** [comment] 2019-09-19 22:10
I believe this is a duplicate of #175.
If I'm incorrect, please re-open this issue with a note.

**Closed by wolenetz** 2019-09-19 22:10 UTC
