### ISSUE TITLE
Low-latency mode

### ISSUE THREAD

**Issue by greentorus** [w3c/media-source#133] opened 2016-08-01 10:23 UTC
Add a flag/mode requesting a low-latency mode (e.g. for videochats or cloud gaming).

When using WebRTC the browser assumes low-latency, but there seems to be no way of telling the browser that you want low-latency with MSE.

**Comment by wolenetz** [comment] 2016-08-01 22:13
Thanks for filing this issue. It's a duplicate of https://github.com/w3c/media-source/issues/21, already on VNext.

Chromium currently has some heuristics for detecting a low-latency video renderer mode signal in each of webm and ISOBMFF bytestream types and using that signal if the rendering path supports low latency, but of course such is not standardized, nor is the current Chromium signal parsing logic final [1] [2] [3]. See #21.

[1] webm: https://cs.chromium.org/chromium/src/media/formats/webm/webm_stream_parser.cc?rcl=0&l=214
[2] isobmff: https://cs.chromium.org/chromium/src/media/formats/mp4/mp4_stream_parser.cc?rcl=0&l=414
[3] (not MSE): https://cs.chromium.org/chromium/src/media/filters/ffmpeg_demuxer.cc?rcl=1470064656&l=1424

**Closed** 2016-08-01 22:13 UTC
Labels: duplicate
